export { default as Header } from './header/header.component'
export { default as Banner } from './banner/banner.component'
export { default as Section } from './section/section.component'
export { default as Movie } from './movie/movie.component'
export { default as Spinner } from './spinner/spinner.component'
export { default as Footer } from './footer/footer.component'
export { default as Slider } from './slider/slider.component'
